### ISSUE TITLE
Libretro port of Gearsystem

### ISSUE THREAD

**Issue by drhelius** [drhelius/Gearsystem#10]
I'm working on this now, it should be pretty straightforward because Gearsystem inherits a lot of code from Gearboy.

But there is a difference though, Gearsystem supports both Master System and Game Gear, which have different resolutions. Even within the Master System catalog there are some games (Codemasters) that output a different resolution.

Any idea of how to implement this in a libretro core @fr500?

**Comment by fr500** [comment]
Hey.

To get started with the core the easiest solution would be to drop-in makefiles and libretro.c and just start.

Regarding resolution changes, you have two callbacks you can use once you know the res has changed, you have to build up a new `struct retro_system_av_info info`, and then call:

```environ_cb(RETRO_ENVIRONMENT_SET_GEOMETRY, &info.geometry);```

You have to populate the info struct with the new geometry of course.
You can do this at any place, even during retro_run, just don't do it on every frame

If you have to change timing you should set RETRO_ENVIRONMENT_SET_AV_INFO instead but don't do it unless it's absolutely necessary because that results in a driver tear down and rebuild, it should be fine once at startup but not during runtime. 

We use this here:
https://github.com/libretro/SameBoy/blob/master/libretro/libretro.c#L651
https://github.com/libretro/SameBoy/blob/master/libretro/libretro.c#L651

To be able to change the dual mode screen layout at runtime.

**Comment by drhelius** [comment]
Te core is working fine now, with all the features, save states, achievements, etc. It' using a fixed resolution for the moment.

I'll have a look at your instructions for changing res, thanks.

**Comment by Hedonium** [comment]
Made a core info file

https://github.com/libretro/libretro-super/pull/758

Working on core documentation too

https://github.com/Hedonium/libretro-docs/commit/50a16c2e65f860e528e5292cb8e2873e407bb37d

**Comment by Hedonium** [comment]
Only things missing from the doc now are accurate fps, sample rate, width, height, aspect ratio values.

Since the core's geometry and timing depends on what content is loaded, you can list values for each combination (PAL games are 50 fps, Game Gear's base height is 144, etc.).

**Comment by drhelius** [comment]
@fr500 Resolution changes are working, the core is finished. 🎉 
I will add more platforms and PR myself to libretro-super

**Comment by orbea** [comment]
I tested the libretro core today, it worked well! Thanks for doing this!
